# name of the object whose information is requested
string name

# set to true if the Geometry should be returned
# with the Object as well. If false, then only
# the current object pose fields are returned
bool get_geometry

---

# true if object exists and information is
# stored in field 'object'
bool success

# information about the object
Object object
